-- Accounts table: Stores customer trading account information
-- Supports multiple account types (ISA, GIA, SIPP)
CREATE TABLE accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          VARCHAR(32) NOT NULL UNIQUE,
    holder_name         VARCHAR(255) NOT NULL,
    cash_balance        NUMERIC(18,2) NOT NULL,
    status              VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    version             INTEGER NOT NULL DEFAULT 0,
    last_updated        TIMESTAMP NOT NULL DEFAULT NOW()
);
