-- Instruments table: Stores tradable financial instruments (stocks, bonds, funds, cash)
CREATE TABLE instruments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol          VARCHAR(20) NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    asset_class     TEXT NOT NULL CHECK (asset_class IN ('EQUITY', 'BOND', 'FUND', 'CASH')),
    currency        TEXT NOT NULL,
    tradable        BOOLEAN NOT NULL
);
