-- Positions table: Stores current holdings for each account
-- Tracks quantity and average cost for portfolio valuation
CREATE TABLE positions (
    position_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT NOT NULL REFERENCES accounts(id),
    symbol          VARCHAR(20) NOT NULL REFERENCES instruments(symbol),
    quantity        NUMERIC(18,4) NOT NULL,
    average_cost    NUMERIC(18,2) NOT NULL,
    UNIQUE (account_id, symbol)
);

CREATE INDEX idx_positions_symbol ON positions(symbol);
