-- Account dimension: Reporting snapshot of account attributes
CREATE TABLE analytics.dim_account (
    account_key         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          BIGINT NOT NULL UNIQUE,
    external_account_id VARCHAR(32) NOT NULL UNIQUE,
    holder_name         VARCHAR(255) NOT NULL,
    status              VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    effective_date      DATE NOT NULL
);

CREATE INDEX idx_dim_account_status ON analytics.dim_account(status);