-- Instrument dimension: Reporting copy of tradable instrument attributes
CREATE TABLE analytics.dim_instrument (
    instrument_key      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol              VARCHAR(20) NOT NULL UNIQUE,
    name                TEXT NOT NULL,
    asset_class         TEXT NOT NULL CHECK (asset_class IN ('EQUITY', 'BOND', 'FUND', 'CASH')),
    currency            TEXT NOT NULL
);

CREATE INDEX idx_dim_instrument_asset_class ON analytics.dim_instrument(asset_class);