-- Trade fact table: Batch-load target built from execution-level activity
CREATE TABLE analytics.fact_trades (
    trade_key           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_execution_id UUID NOT NULL UNIQUE REFERENCES executions(id),
    account_key         BIGINT NOT NULL REFERENCES analytics.dim_account(account_key),
    instrument_key      BIGINT NOT NULL REFERENCES analytics.dim_instrument(instrument_key),
    date_key            INTEGER NOT NULL REFERENCES analytics.dim_date(date_key),
    side                VARCHAR(4) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity            NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    price               NUMERIC(18,2) NOT NULL CHECK (price > 0),
    status              VARCHAR(20) NOT NULL CHECK (status IN ('NEW', 'FILLED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX idx_fact_trades_account_key ON analytics.fact_trades(account_key);
CREATE INDEX idx_fact_trades_instrument_key ON analytics.fact_trades(instrument_key);
CREATE INDEX idx_fact_trades_date_key ON analytics.fact_trades(date_key);